from __future__ import annotations

from algorithms.line import bresenham_line


Point = tuple[int | float, int | float]
Pixel = tuple[int, int]


def sampled_polyline_pixels(points: list[Point]) -> list[Pixel]:
    """Sample a polyline into continuous Bresenham pixels."""
    pixels: list[Pixel] = []
    for start, end in zip(points, points[1:]):
        segment = bresenham_line(round(start[0]), round(start[1]), round(end[0]), round(end[1]))
        if pixels and segment and pixels[-1] == segment[0]:
            pixels.extend(segment[1:])
        else:
            pixels.extend(segment)
    return pixels


def animated_flow_pixels(
    points: list[Point],
    phase: int,
    spacing: int = 24,
    pulse_length: int = 7,
) -> list[Pixel]:
    """Return moving highlight pixels along a sampled route.

    The route itself is still generated by Bresenham pixels. The animation is
    only a phase offset over that stable pixel list.
    """
    pixels = sampled_polyline_pixels(points)
    if not pixels:
        return []
    spacing = max(2, int(spacing))
    pulse_length = max(1, min(int(pulse_length), spacing))
    offset = phase % spacing
    return [point for index, point in enumerate(pixels) if (index - offset) % spacing < pulse_length]
